name: Screenshot Power BI and Send to Telegram - 10:50 BRT

on:
  schedule:
    - cron: '40 13 * * *'  # 10:40 BRT
  workflow_dispatch:

jobs:
  send_1050:
    runs-on: ubuntu-latest
    env:
      API_KEY_TELEGRAM: ${{ secrets.API_KEY_TELEGRAM }}
      CHAT_ID: ${{ secrets.CHAT_ID }}
      CHAT_ID_EDU: ${{ secrets.CHAT_ID_EDU }}
      CHAT_ID_WELL: ${{ secrets.CHAT_ID_WELL }}
      CHAT_GROUP_ID: ${{ secrets.CHAT_GROUP_ID }}
      CHROMIUM_PATH: /usr/bin/chromium
      LINK: https://app.powerbi.com/view?r=eyJrIjoiY2Q3NDU0ZTYtNzBjNS00NzE5LTkzMzEtMGU3ODRhZDc4YjY5IiwidCI6ImQ4NDI2OWQ4LWMxNWUtNGRmMS1iOWRmLTBlNjAzMWMzZjc0YyJ9&pageName=34385227a03acc0a5e40

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      - name: Instalar Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium
      - name: Instalar dependências Node.js
        run: npm ci
      - name: Instalar ImageMagick
        run: sudo apt-get install -y imagemagick
      - name: Dar permissão ao script
        run: chmod +x scripts/tirar_screenshot.sh
      - name: Executar captura e envio para Telegram
        run: bash scripts/tirar_screenshot.sh
