name: Screenshot PowerBI e Envio Telegram

on:
  schedule:
    - cron: '*/15 * * * *'  # Executa a cada 15 minutos
  workflow_dispatch:        # Permite execução manual

jobs:
  screenshot_and_telegram:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4

      - name: Instalar dependências do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser curl

      - name: Instalar dependências Node.js
        run: npm install puppeteer

      - name: Executar script de screenshot e envio para Telegram
        run: bash scripts/tirar_screenshot.sh
